services:
  n8n:
    build: .
    container_name: n8n-puppeteer
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_WEBHOOK_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=debug
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - N8N_METRICS=true
      - N8N_FORMDATA_FILE_SIZE_MAX=1024
      - N8N_PAYLOAD_SIZE_MAX=256
      - TZ=Asia/Dhaka
      - GENERIC_TIMEZONE=Asia/Dhaka
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_CACHE_DIR=/home/node/.cache/puppeteer
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox
    volumes:
      - n8n_storage:/home/node/.n8n
      - n8n_binaries:/home/node/.n8n/binary_data
      - ./shared-data:/shared
      - /mnt/data:/mnt/data

volumes:
  n8n_storage:
  n8n_binaries:
